# Generated by Django 3.0.5 on 2020-05-19 16:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200519_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='join_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
