# Generated by Django 3.0.5 on 2020-05-19 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200519_2032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='fieldName',
            new_name='img',
        ),
    ]
